apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-devops-api
  namespace: ai-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-devops-api
  template:
    metadata:
      labels:
        app: ai-devops-api
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: ai-devops-api
          image: ghcr.io/adithyadspawar/ai-devops-platform:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
