apiVersion: v1
kind: Service
metadata:
  name: ai-devops-service
spec:
  selector:
    app: ai-devops-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
